### ISSUE TITLE
When trying to update to Debian Bookworm, gpio_dnv DKMS step fails.

### ISSUE THREAD

**Issue by sid8tive** [1000001101000/Debian_on_Intel_Terastations#9]
(This issue didn't come up when upgrading from 10 > 11)

make.log contents:

```
DKMS make.log for gpio_dnv-1.0 for kernel 6.1.0-7-amd64 (x86_64)
Fri May  5 10:56:19 AM EDT 2023
make: Entering directory '/usr/src/linux-headers-6.1.0-7-amd64'
  CC [M]  /var/lib/dkms/gpio_dnv/1.0/build/pinctrl-dnv.o
/var/lib/dkms/gpio_dnv/1.0/build/pinctrl-dnv.c: In function ‘dnv_gpio_probe’:
/var/lib/dkms/gpio_dnv/1.0/build/pinctrl-dnv.c:852:23: error: implicit declaration of function ‘gpiochip_irqchip_add’; did you mean ‘gpiochip_irqchip_add_domain’? [-Werror=impli>  852 |                 ret = gpiochip_irqchip_add(gc, &dnv_irqchip, 0,
      |                       ^~~~~~~~~~~~~~~~~~~~
      |                       gpiochip_irqchip_add_domain
/var/lib/dkms/gpio_dnv/1.0/build/pinctrl-dnv.c: In function ‘dnv_irq_set_type’:
/var/lib/dkms/gpio_dnv/1.0/build/pinctrl-dnv.c:530:37: warning: this statement may fall through [-Wimplicit-fallthrough=]
  530 |                         pad_cfg_dw0 |= DNV_RXINV;
/var/lib/dkms/gpio_dnv/1.0/build/pinctrl-dnv.c:531:17: note: here
  531 |                 default:
      |                 ^~~~~~~
cc1: some warnings being treated as errors
make[1]: *** [/usr/src/linux-headers-6.1.0-7-common/scripts/Makefile.build:255: /var/lib/dkms/gpio_dnv/1.0/build/pinctrl-dnv.o] Error 1
make: *** [/usr/src/linux-headers-6.1.0-7-common/Makefile:2037: /var/lib/dkms/gpio_dnv/1.0/build] Error 2
make: Leaving directory '/usr/src/linux-headers-6.1.0-7-amd64'
```

**Comment by 1000001101000** [comment]
If you update pinctrl-dnv.c to the latest version from the repository it should build successfully

**Comment by sid8tive** [comment]
Thank you! (in hindsight, I should have tried that first) It works with the new file!
